//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomingoDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Destination
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Tagline { get; set; }
        public string Description { get; set; }
        public string ThumbnailPath { get; set; }
        public string CircuitUrl { get; set; }
        public string BestTimeToVisit { get; set; }
        public string TravelStyles { get; set; }
        public string TemplateSearchAlias { get; set; }
        public string TourContinent { get; set; }
        public int Weightage { get; set; }
        public string Alias { get; set; }
        public string MetaDescription { get; set; }
        public string MetaKeywords { get; set; }
        public string Country { get; set; }
        public string ShortDescription { get; set; }
    }
}
