//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomingoDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DestinationLink
    {
        public int Id { get; set; }
        public int SourceDestinationId { get; set; }
        public int FinalDestinationId { get; set; }
        public string LinkDetail { get; set; }
        public string LinkType { get; set; }
    }
}
