//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomingoDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HtmlEmail
    {
        public int Id { get; set; }
        public int HtmlEmailTemplateId { get; set; }
        public string EmailText { get; set; }
        public string EmailSubject { get; set; }
        public string EmailTitle { get; set; }
        public int MessageTypeId { get; set; }
        public string FromAddress { get; set; }
        public string FromName { get; set; }
        public string ToAddress { get; set; }
    
        public virtual HtmlEmailTemplate HtmlEmailTemplate { get; set; }
    }
}
