//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomingoDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Place
    {
        public int Id { get; set; }
        public int RegionId { get; set; }
        public int CountryId { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> Lattitude { get; set; }
        public Nullable<decimal> Longitude { get; set; }
        public string ShortDescription { get; set; }
        public string LongDescription { get; set; }
        public string Attractions { get; set; }
        public string Activities { get; set; }
        public string State { get; set; }
        public Nullable<int> Beach { get; set; }
        public Nullable<int> Mountain { get; set; }
        public Nullable<int> Trekking { get; set; }
        public Nullable<int> Nightlife { get; set; }
        public Nullable<int> Wildlife { get; set; }
        public Nullable<int> Desert { get; set; }
        public Nullable<int> Culture { get; set; }
        public Nullable<int> Motorcycle { get; set; }
        public Nullable<int> History { get; set; }
        public Nullable<int> Spiritual { get; set; }
        public Nullable<int> SocialWork { get; set; }
        public Nullable<int> UsualDays { get; set; }
    }
}
