//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomingoDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThreadMessage
    {
        public int Id { get; set; }
        public int ThreadId { get; set; }
        public string Body { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int AuthorUserId { get; set; }
        public int ModerationStatus { get; set; }
        public int TodoCompleted { get; set; }
        public Nullable<int> brickid { get; set; }
        public Nullable<int> ModerationStatusChangedByUserId { get; set; }
        public Nullable<System.DateTime> ModerationStatusChangedDate { get; set; }
    }
}
