//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomingoDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transit
    {
        public int Id { get; set; }
        public int SourceId { get; set; }
        public int DestinationId { get; set; }
        public Nullable<decimal> Distance { get; set; }
        public string departure_stop { get; set; }
        public string departure_time { get; set; }
        public string arrival_stop { get; set; }
        public string arrival_time { get; set; }
        public Nullable<decimal> Transit_Time { get; set; }
        public string Mode { get; set; }
        public string Description { get; set; }
    }
}
