//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomingoDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TripStep
    {
        public int Id { get; set; }
        public int TripId { get; set; }
        public string Destination { get; set; }
        public int SortOrder { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public int TripTemplateStepId { get; set; }
        public string ShortDescription { get; set; }
        public string LongDescription { get; set; }
        public string NightStay { get; set; }
        public string TravellerNote { get; set; }
        public string TravelogerNote { get; set; }
        public int TripTemplateId { get; set; }
    }
}
