//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomingoDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trip
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public string StartLocation { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string EndLocation { get; set; }
        public int Travellerid { get; set; }
        public string AspNetUserId { get; set; }
        public Nullable<int> ThreadId { get; set; }
        public string Description { get; set; }
        public int PaxAdults { get; set; }
        public Nullable<int> PaxMinors { get; set; }
        public string TripType { get; set; }
        public string TemplateSearchAlias { get; set; }
        public int DestinationId { get; set; }
        public string Templates { get; set; }
        public string NickName { get; set; }
        public string TripCurrency { get; set; }
        public Nullable<decimal> EstimatedCost { get; set; }
        public string HomeLocation { get; set; }
    }
}
