//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomingoDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TripV2
    {
        public int Id { get; set; }
        public string SessionId { get; set; }
        public string AspNetUserId { get; set; }
        public string Preferences { get; set; }
        public Nullable<int> PaxAdults { get; set; }
        public Nullable<int> PaxMinors { get; set; }
        public string TripCurrency { get; set; }
        public Nullable<decimal> EstimatedCost { get; set; }
        public string HomeLocation { get; set; }
    }
}
