//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomingoDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TripProvider
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Website { get; set; }
        public string Address { get; set; }
        public string EmailAddressPrimary { get; set; }
        public string EmailAddressMarketingSales { get; set; }
        public string EmailAddressCustSupport { get; set; }
        public string Description { get; set; }
        public string Telephone01 { get; set; }
        public string Telephone02 { get; set; }
        public string Telephone03 { get; set; }
        public string Type { get; set; }
    }
}
