//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomingoDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_TripStepCost
    {
        public int TripId { get; set; }
        public int TripStepId { get; set; }
        public string ShortDescription { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> ActualDays { get; set; }
        public int TypicalDurationDays { get; set; }
        public decimal ACCO_COST { get; set; }
        public string ACCO_CURRENCY { get; set; }
        public string ACCO_SEASON { get; set; }
        public decimal TRANSPORT_COST { get; set; }
        public string TRANSPORT_CURRENCY { get; set; }
        public string TRANSPORT_SEASON { get; set; }
        public decimal FOOD_COST { get; set; }
        public string FOOD_CURRENCY { get; set; }
        public string FOOD_SEASON { get; set; }
    }
}
